let requestData = {
    no: '',
    year: '',
    menu: ''
}
let raw_request_data = {
    REQUEST_NO: '',
    REQUEST_YEAR: '',
    PERSONAL_ID_OWNER: '',
    REQUEST_TYPE_ID: '',
    STAFF_ID_ALDERMAN: '',
    ESTABLISHMENT_ID: '',
    STAFF_ID_MONEY: '',
    REFERENCE_ID: '',
    TRAIN_ID: '',
    PERSONAL_ID_ASSISTANT: '',
    STAFF_ID_APPROVE: '',
    ESTABLISHMENT_IS_LAND_OWNED: '',
    ESTABLISHMENT_ADDRESS_ID: '',
    REQUEST_MENU: '',
    REQUEST_DATE_SUBMISSION: '',
    REQUEST_DATE_APPROVE: '',
    REQUEST_DOC_NO1: '',
    REQUEST_DOC_NO2: '',
    REQUEST_DOC_NO3: '',
    REQUEST_DOC_NO4: '',
    REQUEST_DOC_NO5: '',
    REQUEST_DOC_NO6: '',
    REQUEST_SUBCATEGORY: '',
    REQUEST_PRODUCT_TYPE: '',
    REQUEST_SELL_START: '',
    REQUEST_SELL_END: '',
    REQUEST_SELL_ALLOW: '',
    REQUEST_RECEIPT_FINE: '',
    REQUEST_RECEIPT_FEE: '',
    REQUEST_RECEIPT_TOTAL: '',
    REQUEST_RECEIPT_FINE_YEAR_2: '',
    REQUEST_RECEIPT_FEE_YEAR_2: '',
    REQUEST_RECEIPT_TOTAL_YEAR_2: '',
    REQUEST_RECEIPT_DATE_YEAR_2: '',
    REQUEST_RECEIPT_FINE_YEAR_3: '',
    REQUEST_RECEIPT_FEE_YEAR_3: '',
    REQUEST_RECEIPT_TOTAL_YEAR_3: '',
    REQUEST_RECEIPT_FINE_TRANSFER: '',
    REQUEST_RECEIPT_DATE_TRANSFER: '',
    REQUEST_RECEIPT_DATE_YEAR_3: '',
    REQUEST_RECEIPT_DATE: '',
    REQUEST_DATE_ISSUED: '',
    REQUEST_DATE_EXPIRED: '',
    REQUEST_CONDITION_NO_1: '',
    REQUEST_CONDITION_NO_2: '',
    REQUEST_CONDITION_NO_3: '',
    REQUEST_CONDITION_NO_4: '',
    REQUEST_IMAGE_NAME: '',
    REQUEST_TOTAL_IMAGE: '',
    REQUEST_STATUS: '',
    REQUEST_STATUS_BEFORE: '',
    REQUEST_DELETE_LOGIC: '',
    REQUEST_IS_DELETED: ''
}
let operatorAddressData = {
    is_address_changed: false,
    id: "",
    home_number: "",
    moo: '',
    trxk: '',
    sxy: '',
    building: '',
    road: '',
    district_name: "",
    amphur_name: "",
    province_name: ""
};
let operatorData = {
    is_personal_changed: false,
    id: "",
    address_id: "",
    title: "",
    type: "",
    name: "",
    surname: "",
    nationality: '',
    race: '',
    birthday: '',
    personal_id: "",
    card_issued: "",
    card_expipe: '',
    phone: "",
    fax: ''
};
let operatorAddressDataN = {
    is_address_changed: false,
    id: "",
    home_number: "",
    moo: '',
    trxk: '',
    sxy: '',
    building: '',
    road: '',
    district_name: "",
    amphur_name: "",
    province_name: ""
};
let operatorDataN = {
    is_personal_changed: false,
    id: "",
    address_id: "",
    title: "",
    type: "",
    name: "",
    surname: "",
    nationality: '',
    race: '',
    birthday: '',
    personal_id: "",
    card_issued: "",
    card_expipe: '',
    phone: "",
    fax: ''
};
function resetRequestData() {
    requestData = {
        no: '',
        year: '',
        menu: ''
    }
    raw_request_data = {
        REQUEST_NO: '',
        REQUEST_YEAR: '',
        PERSONAL_ID_OWNER: '',
        REQUEST_TYPE_ID: '',
        STAFF_ID_ALDERMAN: '',
        ESTABLISHMENT_ID: '',
        STAFF_ID_MONEY: '',
        REFERENCE_ID: '',
        TRAIN_ID: '',
        PERSONAL_ID_ASSISTANT: '',
        STAFF_ID_APPROVE: '',
        ESTABLISHMENT_IS_LAND_OWNED: '',
        ESTABLISHMENT_ADDRESS_ID: '',
        REQUEST_MENU: '',
        REQUEST_DATE_SUBMISSION: '',
        REQUEST_DATE_APPROVE: '',
        REQUEST_DOC_NO1: '',
        REQUEST_DOC_NO2: '',
        REQUEST_DOC_NO3: '',
        REQUEST_DOC_NO4: '',
        REQUEST_DOC_NO5: '',
        REQUEST_DOC_NO6: '',
        REQUEST_SUBCATEGORY: '',
        REQUEST_PRODUCT_TYPE: '',
        REQUEST_SELL_START: '',
        REQUEST_SELL_END: '',
        REQUEST_SELL_ALLOW: '',
        REQUEST_RECEIPT_FINE: '',
        REQUEST_RECEIPT_FEE: '',
        REQUEST_RECEIPT_TOTAL: '',
        REQUEST_RECEIPT_FINE_YEAR_2: '',
        REQUEST_RECEIPT_FEE_YEAR_2: '',
        REQUEST_RECEIPT_TOTAL_YEAR_2: '',
        REQUEST_RECEIPT_DATE_YEAR_2: '',
        REQUEST_RECEIPT_FINE_YEAR_3: '',
        REQUEST_RECEIPT_FEE_YEAR_3: '',
        REQUEST_RECEIPT_TOTAL_YEAR_3: '',
        REQUEST_RECEIPT_FINE_TRANSFER: '',
        REQUEST_RECEIPT_DATE_TRANSFER: '',
        REQUEST_RECEIPT_DATE_YEAR_3: '',
        REQUEST_RECEIPT_DATE: '',
        REQUEST_DATE_ISSUED: '',
        REQUEST_DATE_EXPIRED: '',
        REQUEST_CONDITION_NO_1: '',
        REQUEST_CONDITION_NO_2: '',
        REQUEST_CONDITION_NO_3: '',
        REQUEST_CONDITION_NO_4: '',
        REQUEST_IMAGE_NAME: '',
        REQUEST_TOTAL_IMAGE: '',
        REQUEST_STATUS: '',
        REQUEST_STATUS_BEFORE: '',
        REQUEST_DELETE_LOGIC: '',
        REQUEST_IS_DELETED: ''
    }
    operatorAddressData = {
        is_address_changed: false,
        id: "",
        home_number: "",
        moo: '',
        trxk: '',
        sxy: '',
        building: '',
        road: '',
        district_name: "",
        amphur_name: "",
        province_name: ""
    };
    operatorData = {
        is_personal_changed: false,
        id: "",
        address_id: "",
        title: "",
        type: "",
        name: "",
        surname: "",
        nationality: '',
        race: '',
        birthday: '',
        personal_id: "",
        card_issued: "",
        card_expipe: '',
        phone: "",
        fax: ''
    };
    operatorAddressDataN = {
        is_address_changed: false,
        id: "",
        home_number: "",
        moo: '',
        trxk: '',
        sxy: '',
        building: '',
        road: '',
        district_name: "",
        amphur_name: "",
        province_name: ""
    };
    operatorDataN = {
        is_personal_changed: false,
        id: "",
        address_id: "",
        title: "",
        type: "",
        name: "",
        surname: "",
        nationality: '',
        race: '',
        birthday: '',
        personal_id: "",
        card_issued: "",
        card_expipe: '',
        phone: "",
        fax: ''
    };
}

function resetRequest(){
    requestData = {
        no: '',
        year: '',
        menu: ''
    }
    raw_request_data = {
        REQUEST_NO: '',
        REQUEST_YEAR: '',
        PERSONAL_ID_OWNER: '',
        REQUEST_TYPE_ID: '',
        STAFF_ID_ALDERMAN: '',
        ESTABLISHMENT_ID: '',
        STAFF_ID_MONEY: '',
        REFERENCE_ID: '',
        TRAIN_ID: '',
        PERSONAL_ID_ASSISTANT: '',
        STAFF_ID_APPROVE: '',
        ESTABLISHMENT_IS_LAND_OWNED: '',
        ESTABLISHMENT_ADDRESS_ID: '',
        REQUEST_MENU: '',
        REQUEST_DATE_SUBMISSION: '',
        REQUEST_DATE_APPROVE: '',
        REQUEST_DOC_NO1: '',
        REQUEST_DOC_NO2: '',
        REQUEST_DOC_NO3: '',
        REQUEST_DOC_NO4: '',
        REQUEST_DOC_NO5: '',
        REQUEST_DOC_NO6: '',
        REQUEST_SUBCATEGORY: '',
        REQUEST_PRODUCT_TYPE: '',
        REQUEST_SELL_START: '',
        REQUEST_SELL_END: '',
        REQUEST_SELL_ALLOW: '',
        REQUEST_RECEIPT_FINE: '',
        REQUEST_RECEIPT_FEE: '',
        REQUEST_RECEIPT_TOTAL: '',
        REQUEST_RECEIPT_FINE_YEAR_2: '',
        REQUEST_RECEIPT_FEE_YEAR_2: '',
        REQUEST_RECEIPT_TOTAL_YEAR_2: '',
        REQUEST_RECEIPT_DATE_YEAR_2: '',
        REQUEST_RECEIPT_FINE_YEAR_3: '',
        REQUEST_RECEIPT_FEE_YEAR_3: '',
        REQUEST_RECEIPT_TOTAL_YEAR_3: '',
        REQUEST_RECEIPT_FINE_TRANSFER: '',
        REQUEST_RECEIPT_DATE_TRANSFER: '',
        REQUEST_RECEIPT_DATE_YEAR_3: '',
        REQUEST_RECEIPT_DATE: '',
        REQUEST_DATE_ISSUED: '',
        REQUEST_DATE_EXPIRED: '',
        REQUEST_CONDITION_NO_1: '',
        REQUEST_CONDITION_NO_2: '',
        REQUEST_CONDITION_NO_3: '',
        REQUEST_CONDITION_NO_4: '',
        REQUEST_IMAGE_NAME: '',
        REQUEST_TOTAL_IMAGE: '',
        REQUEST_STATUS: '',
        REQUEST_STATUS_BEFORE: '',
        REQUEST_DELETE_LOGIC: '',
        REQUEST_IS_DELETED: ''
    }
}